---
  # - name: check param VAR_OS_gathering_rolename is none
    # fail:
      # msg: "Parameter VAR_IIS_gathering_rolename cannot be NULL."
    # when: "(VAR_IIS_gathering_rolename is none) or (VAR_IIS_gathering_rolename == '')"

  - name: Remove old data
    file:
      path: "{{ VAR_IIS_gathering_dest }}/{{ inventory_hostname }}/IIS_WS2016_gathering"
      state: absent
    delegate_to: localhost
    become: no

  - name: include tasks
    include_tasks: gather.yml
    # with_items: "{{ VAR_IIS_gathering_rolename }}"
    # loop_control:
      # loop_var: outer_item